<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use 
Illuminate\support\facades\DB;
 

class matterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
{
    DB::table('matters')->insert([
        [
            'matter_reference' => 'HM-2026-001',
            'title' => 'District Security Assessment',
            'section' => 'Monitoring',
            'category' => 'Security',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 01',
            'related_department' => 'Police',
            'received_date' => '2026-09-15',
            'deadline' => '2026-09-25',
            'summary' => 'Synthetic assessment record for demonstration purposes.',
            'last_action' => 'Information requested from concerned office.',
            'next_action' => 'Review submitted information.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-002',
            'title' => 'Security Coordination Review',
            'section' => 'Internal Security',
            'category' => 'Coordination',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 02',
            'related_department' => 'Police',
            'received_date' => '2026-09-12',
            'deadline' => '2026-09-28',
            'summary' => 'Synthetic coordination matter for the executive dashboard.',
            'last_action' => 'Coordination meeting requested.',
            'next_action' => 'Review meeting outcomes.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-003',
            'title' => 'Public Grievance Review',
            'section' => 'Monitoring',
            'category' => 'Public Grievance',
            'priority' => 'Normal',
            'district' => 'Hyderabad',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 03',
            'related_department' => 'District Administration',
            'received_date' => '2026-09-10',
            'deadline' => '2026-09-26',
            'summary' => 'Synthetic public grievance review.',
            'last_action' => 'Complaint referred for response.',
            'next_action' => 'Review response.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-004',
            'title' => 'Prison Capacity Review',
            'section' => 'Prison',
            'category' => 'Prison Administration',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 04',
            'related_department' => 'Prisons',
            'received_date' => '2026-09-08',
            'deadline' => '2026-09-24',
            'summary' => 'Synthetic prison capacity review.',
            'last_action' => 'Data requested from concerned office.',
            'next_action' => 'Analyze submitted data.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-005',
            'title' => 'Civil Defence Preparedness Review',
            'section' => 'Civil Defence',
            'category' => 'Preparedness',
            'priority' => 'Normal',
            'district' => 'Sukkur',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 05',
            'related_department' => 'Civil Defence',
            'received_date' => '2026-09-05',
            'deadline' => '2026-10-02',
            'summary' => 'Synthetic preparedness review.',
            'last_action' => 'Inspection schedule prepared.',
            'next_action' => 'Review inspection findings.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-006',
            'title' => 'Arms Licensing Review',
            'section' => 'Arms',
            'category' => 'Licensing',
            'priority' => 'Normal',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 06',
            'related_department' => 'Administration',
            'received_date' => '2026-09-03',
            'deadline' => '2026-09-30',
            'summary' => 'Synthetic licensing review record.',
            'last_action' => 'Documents received for review.',
            'next_action' => 'Complete administrative review.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-007',
            'title' => 'Religious Event Security Coordination',
            'section' => 'Internal Security',
            'category' => 'Event Security',
            'priority' => 'High',
            'district' => 'Thatta',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 07',
            'related_department' => 'Police',
            'received_date' => '2026-09-14',
            'deadline' => '2026-09-23',
            'summary' => 'Synthetic event coordination matter.',
            'last_action' => 'Security plan requested.',
            'next_action' => 'Review submitted plan.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-008',
            'title' => 'Foreigners Registration Review',
            'section' => 'Foreigner',
            'category' => 'Administration',
            'priority' => 'Normal',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 08',
            'related_department' => 'Immigration',
            'received_date' => '2026-09-01',
            'deadline' => '2026-10-05',
            'summary' => 'Synthetic administrative review.',
            'last_action' => 'Information compiled.',
            'next_action' => 'Complete review.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-009',
            'title' => 'Meeting Action Follow-up',
            'section' => 'Administration',
            'category' => 'Follow-up',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 09',
            'related_department' => 'Multiple Departments',
            'received_date' => '2026-09-16',
            'deadline' => '2026-09-27',
            'summary' => 'Synthetic meeting action follow-up.',
            'last_action' => 'Action points circulated.',
            'next_action' => 'Collect departmental updates.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-010',
            'title' => 'Human Rights Matter Review',
            'section' => 'Monitoring',
            'category' => 'Human Rights',
            'priority' => 'High',
            'district' => 'Larkana',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 10',
            'related_department' => 'District Administration',
            'received_date' => '2026-09-07',
            'deadline' => '2026-09-29',
            'summary' => 'Synthetic monitoring matter.',
            'last_action' => 'Initial report received.',
            'next_action' => 'Review report and response.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-011',
            'title' => 'Police Coordination Matter',
            'section' => 'Police',
            'category' => 'Coordination',
            'priority' => 'Normal',
            'district' => 'Mirpurkhas',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 11',
            'related_department' => 'Police',
            'received_date' => '2026-09-06',
            'deadline' => '2026-10-01',
            'summary' => 'Synthetic police coordination matter.',
            'last_action' => 'Request forwarded.',
            'next_action' => 'Await response.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-012',
            'title' => 'Apex Committee Meeting Preparation',
            'section' => 'Internal Security',
            'category' => 'Meeting',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 12',
            'related_department' => 'Multiple Departments',
            'received_date' => '2026-09-17',
            'deadline' => '2026-09-30',
            'summary' => 'Synthetic meeting preparation matter.',
            'last_action' => 'Agenda items collected.',
            'next_action' => 'Prepare executive brief.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-013',
            'title' => 'Public Complaint Response',
            'section' => 'Monitoring',
            'category' => 'Public Grievance',
            'priority' => 'Normal',
            'district' => 'Nawabshah',
            'status' => 'Closed',
            'assigned_officer' => 'Demo Officer 13',
            'related_department' => 'District Administration',
            'received_date' => '2026-08-28',
            'deadline' => '2026-09-12',
            'summary' => 'Synthetic complaint record completed.',
            'last_action' => 'Response reviewed.',
            'next_action' => 'No further action required.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-014',
            'title' => 'Facility Safety Inspection',
            'section' => 'Civil Defence',
            'category' => 'Inspection',
            'priority' => 'Normal',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 14',
            'related_department' => 'Civil Defence',
            'received_date' => '2026-09-11',
            'deadline' => '2026-10-03',
            'summary' => 'Synthetic safety inspection matter.',
            'last_action' => 'Inspection request received.',
            'next_action' => 'Schedule inspection.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-015',
            'title' => 'Parole Review Matter',
            'section' => 'Prison',
            'category' => 'Parole',
            'priority' => 'Normal',
            'district' => 'Hyderabad',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 15',
            'related_department' => 'Prisons',
            'received_date' => '2026-09-13',
            'deadline' => '2026-09-28',
            'summary' => 'Synthetic parole review record.',
            'last_action' => 'Required documents requested.',
            'next_action' => 'Review submitted documents.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-016',
            'title' => 'NGO Coordination Review',
            'section' => 'Internal Security',
            'category' => 'NGO Coordination',
            'priority' => 'Normal',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 16',
            'related_department' => 'Administration',
            'received_date' => '2026-09-04',
            'deadline' => '2026-10-06',
            'summary' => 'Synthetic NGO coordination record.',
            'last_action' => 'Information received.',
            'next_action' => 'Complete review.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-017',
            'title' => 'Security Report Follow-up',
            'section' => 'Monitoring',
            'category' => 'Monitoring',
            'priority' => 'High',
            'district' => 'Sukkur',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 17',
            'related_department' => 'Police',
            'received_date' => '2026-09-18',
            'deadline' => '2026-09-24',
            'summary' => 'Synthetic security monitoring record.',
            'last_action' => 'Follow-up requested.',
            'next_action' => 'Review incoming report.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-018',
            'title' => 'Administrative Correspondence Review',
            'section' => 'Administration',
            'category' => 'Correspondence',
            'priority' => 'Low',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 18',
            'related_department' => 'Administration',
            'received_date' => '2026-09-02',
            'deadline' => '2026-10-08',
            'summary' => 'Synthetic administrative correspondence.',
            'last_action' => 'File placed for review.',
            'next_action' => 'Review correspondence.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-019',
            'title' => 'Departmental Budget Review',
            'section' => 'Budget',
            'category' => 'Finance',
            'priority' => 'Normal',
            'district' => 'Karachi',
            'status' => 'Open',
            'assigned_officer' => 'Demo Officer 19',
            'related_department' => 'Finance',
            'received_date' => '2026-09-09',
            'deadline' => '2026-10-04',
            'summary' => 'Synthetic departmental budget matter.',
            'last_action' => 'Budget information requested.',
            'next_action' => 'Review submitted figures.',
            'created_at' => now(),
            'updated_at' => now(),
        ],

        [
            'matter_reference' => 'HM-2026-020',
            'title' => 'Executive Decision Follow-up',
            'section' => 'Administration',
            'category' => 'Executive Direction',
            'priority' => 'High',
            'district' => 'Karachi',
            'status' => 'Pending',
            'assigned_officer' => 'Demo Officer 20',
            'related_department' => 'Multiple Departments',
            'received_date' => '2026-09-19',
            'deadline' => '2026-09-26',
            'summary' => 'Synthetic executive decision follow-up.',
            'last_action' => 'Matter placed for executive consideration.',
            'next_action' => 'Record executive direction.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
}
}
